### ISSUE TITLE
haymarketers - Windows

### ISSUE THREAD

**Issue by PacketMonkey22** [redhataugust/VulnHub_Vagrant#1]
Just need to save a .bat file with the following one line below in it for a 'script' or just copy/paste into command prompt.

"C:\Program Files\Oracle\VirtualBox\vboxmanage.exe" dhcpserver add --netname haymarketers --ip 10.13.37.1 --netmask 255.255.255.0 --lowerip 10.13.37.5 --upperip 10.13.37.254 --enable

**Comment by redhataugust** [comment]
Understood. I'll get to the scripts at a later time. Otherwise, you are correct. This can be handled as a copy/paste so long as you installed VBox in the default location.
