### ISSUE TITLE
error when starting firstblood

### ISSUE THREAD

**Issue by PacketMonkey22** [redhataugust/VulnHub_Vagrant#2]
Didn't know what vagrant was but I believe I installed it. Below is what I did to get it to launch a VM. Also, when I ran firstblood on my home PC, I had the same error of which turning off usb 2.0 resolved it.

Download and install from https://www.vagrantup.com/downloads
Install will have you reboot but you can say no
Open CMD
type vagrant
should get results, confirmed works
Download and install (default options) from https://gitforwindows.org/
select launch git at end
cd to folder you want to download VulnHub_Vagrant
git clone https://github.com/redhataugust/VulnHub_Vagrant  (less than 200KB)
close git
go back to CMD
cd "C:\github\redhataugust\VulnHub_Vagrant"  (or your folder name)
cd 2020-09-19_FirstBlood-1
vagrant up

You will see:
_Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'RedHatAugust/FirstBlood-1' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'RedHatAugust/FirstBlood-1'
    default: URL: https://vagrantcloud.com/RedHatAugust/FirstBlood-1
==> default: Adding box 'RedHatAugust/FirstBlood-1' (v0.01) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/RedHatAugust/boxes/FirstBlood-1/versions/0.01/providers/virtualbox.box
Download redirected to host:..._

UAC prompt then copying files box then UAC prompt

    _default:
    default: Calculating and comparing box checksum...
==> default: Successfully added box 'RedHatAugust/FirstBlood-1' (v0.01) for 'virtualbox'!
==> default: Importing base box 'RedHatAugust/FirstBlood-1'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'RedHatAugust/FirstBlood-1' version '0.01' is up to date...
==> default: Setting the name of the VM: FirstBlood
Vagrant is currently configured to create VirtualBox synced folders with
the `SharedFoldersEnableSymlinksCreate` option enabled. If the Vagrant
guest is not trusted, you may want to disable this option. For more
information on this option, please refer to the VirtualBox manual:

  https://www.virtualbox.org/manual/ch04.html#sharedfolders

This option can be disabled globally with an environment variable:

  VAGRANT_DISABLE_VBOXSYMLINKCREATE=1

or on a per folder basis within the Vagrantfile:

  config.vm.synced_folder '/host/path', '/guest/path', SharedFoldersEnableSymlinksCreate: false
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
    default: Adapter 1: intnet
    default: Adapter 2: intnet
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
    default: VirtualBox adapter #1 not configured as "NAT". Skipping port
    default: forwards on this adapter.
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "ef715adf-b587-4099-914a-ab4417c4dbff", "--type", "headless"]

Stderr: VBoxManage.exe: error: Implementation of the USB 2.0 controller not found!_
**VBoxManage.exe: error: Because the USB 2.0 controller state is part of the saved VM state, the VM cannot be started. To fix this problem, either install the 'Oracle VM VirtualBox Extension Pack' or disable USB 2.0 support in the VM settings.**
_VBoxManage.exe: error: Note! This error could also mean that an incompatible version of the 'Oracle VM VirtualBox Extension Pack' is installed (VERR_NOT_FOUND)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole_

**Comment by PacketMonkey22** [comment]
tried 2020-04-22_Broken-2020-1 next.

Stops at
 default: SSH username: vagrant
    default: SSH auth method: private key

not sure what to do after that.

edit:

might be helpful if I open virtual box

**Comment by redhataugust** [comment]
Aw yes. Thank you for bringing this to my attention. Without removing the USB 2.0 adapter (which you actually don't need anyway), can you try installing the VirtualBox Extension Pack for your version? You'll see it in the middle of the downloads page: https://www.virtualbox.org/wiki/Downloads. Let me know if this allows it to boot without you needing to modify the VM settings. Also, as in the README, ssh will not work with Vagrant. You'll have to hack into the machine as per usual - with another VM on the haymarketers network.

**Comment by PacketMonkey22** [comment]
...run below, you need admin. 
..virtualbox as admin then ran below, you need admin. sigh.
open cmd as admin then cd to downloads then run below, installed.

https://download.virtualbox.org/virtualbox/6.1.14/Oracle_VM_VirtualBox_Extension_Pack-6.1.14.vbox-extpack

...all these things needing admin rights pointlessly.

new CMD, cd 2020-09-19_FirstBlood-1
vagrant up
ctrl+c on ssh
open virtual box
its running

**Comment by redhataugust** [comment]
I'm not sure why you are feeling that there is unnecessary usage of admin privileges. To be clear, you must have admin rights to install any of the applications aforementioned. Beyond that, you shouldn't need admin rights at all... (not even for the internal network creation). I went ahead and tested my thoughts out and arrived at the same conclusion as what I am stating here. 
Once you have the applications installed, do not open anything as admin. UAC should not prompt you, as well. It seems as though this is now working for you, so I will close this issue.
